POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jessica",
    "number": "12-12-1234567"
}

###

PUT http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Jessica",
    "number": "82-741852963"
}

###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/