POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jessica",
    "number": "12-12-1234567"
}

###

PUT http://localhost:3001/api/persons/60ed6d041259483a5ce624b2
Content-Type: application/json

{
    "name": "Jessica",
    "number": "82-741852963"
}

###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/60ed6d041259483a5ce624b2

###

GET http://localhost:3001/api/persons/60ed6cb5daf7de24300bd64c